// Embedded dictionary used by the adaptive engine.
// ~400 short common English words (2-6 letters), all lowercase.
// Chosen for: high frequency, full coverage of letter combinations, no
// proper nouns, no offensive vocabulary, no inflections that wouldn't be
// useful for typing practice.

export const WORD_LIST: readonly string[] = [
  // 2-letter
  'an', 'as', 'at', 'be', 'by', 'do', 'go', 'he', 'if', 'in', 'is', 'it',
  'me', 'my', 'no', 'of', 'on', 'or', 'so', 'to', 'up', 'us', 'we',

  // 3-letter
  'all', 'and', 'any', 'are', 'arm', 'art', 'ask', 'bad', 'bag', 'bar', 'bat',
  'bed', 'big', 'bit', 'box', 'boy', 'bus', 'but', 'buy', 'can', 'car', 'cat',
  'cup', 'cut', 'day', 'did', 'dog', 'dry', 'ear', 'eat', 'egg', 'end', 'eye',
  'far', 'few', 'fly', 'for', 'fun', 'gas', 'get', 'god', 'got', 'gun', 'guy',
  'had', 'has', 'hat', 'her', 'hey', 'him', 'his', 'hit', 'hot', 'how', 'ice',
  'its', 'job', 'key', 'kid', 'lab', 'law', 'lay', 'leg', 'let', 'lie', 'lot',
  'low', 'man', 'map', 'may', 'men', 'mom', 'new', 'nor', 'not', 'now', 'odd',
  'off', 'oil', 'old', 'one', 'our', 'out', 'own', 'pay', 'pen', 'per', 'put',
  'ran', 'red', 'run', 'sad', 'sat', 'say', 'sea', 'see', 'set', 'she', 'sit',
  'six', 'sky', 'son', 'sun', 'tax', 'tea', 'ten', 'the', 'tip', 'too', 'top',
  'toy', 'try', 'two', 'use', 'van', 'war', 'was', 'way', 'web', 'who', 'why',
  'win', 'yes', 'yet', 'you',

  // 4-letter
  'able', 'also', 'area', 'army', 'away', 'baby', 'back', 'ball', 'band', 'bank',
  'base', 'beat', 'been', 'best', 'bill', 'bird', 'blue', 'boat', 'body', 'book',
  'born', 'both', 'bowl', 'busy', 'call', 'calm', 'came', 'card', 'care', 'case',
  'cash', 'cell', 'city', 'club', 'cold', 'come', 'cool', 'cost', 'crew', 'dark',
  'data', 'date', 'dead', 'deal', 'dear', 'debt', 'deep', 'desk', 'does', 'done',
  'door', 'down', 'draw', 'drop', 'dust', 'duty', 'each', 'earn', 'easy', 'edge',
  'else', 'even', 'ever', 'face', 'fact', 'fail', 'fair', 'fall', 'farm', 'fast',
  'fear', 'feel', 'fell', 'felt', 'file', 'fill', 'find', 'fine', 'fire', 'fish',
  'five', 'flag', 'flat', 'flow', 'food', 'foot', 'form', 'four', 'free', 'from',
  'full', 'fund', 'gain', 'game', 'gave', 'girl', 'give', 'glad', 'goal', 'goes',
  'gold', 'gone', 'good', 'gray', 'grow', 'half', 'hand', 'hard', 'have', 'head',
  'hear', 'heat', 'held', 'help', 'here', 'high', 'hill', 'hold', 'hole', 'home',
  'hope', 'host', 'hour', 'huge', 'hunt', 'idea', 'into', 'iron', 'item', 'join',
  'jump', 'just', 'keep', 'kept', 'kind', 'king', 'knee', 'knew', 'know', 'lack',
  'lady', 'laid', 'lake', 'land', 'last', 'late', 'lead', 'left', 'less', 'life',
  'lift', 'like', 'line', 'link', 'list', 'live', 'load', 'lock', 'long', 'look',
  'lord', 'lose', 'loss', 'lost', 'loud', 'love', 'made', 'mail', 'main', 'make',
  'many', 'mark', 'mass', 'meal', 'mean', 'meat', 'meet', 'mile', 'milk', 'mind',
  'mine', 'miss', 'mode', 'mood', 'more', 'most', 'move', 'much', 'must', 'name',
  'navy', 'near', 'neck', 'need', 'news', 'next', 'nice', 'nine', 'none', 'nose',
  'note', 'okay', 'once', 'only', 'onto', 'open', 'over', 'pace', 'pack', 'page',
  'paid', 'pain', 'pair', 'park', 'part', 'pass', 'past', 'path', 'pick', 'pink',
  'plan', 'play', 'plot', 'plus', 'poem', 'poor', 'port', 'post', 'pull', 'pure',
  'push', 'quit', 'race', 'rain', 'rare', 'rate', 'read', 'real', 'rest', 'rich',
  'ride', 'ring', 'rise', 'risk', 'road', 'rock', 'role', 'roll', 'roof', 'room',
  'root', 'rose', 'rule', 'safe', 'said', 'sail', 'sake', 'sale', 'salt', 'same',
  'sand', 'save', 'seat', 'seed', 'seek', 'seem', 'seen', 'self', 'sell', 'send',
  'shall', 'shop', 'shot', 'show', 'sick', 'side', 'sign', 'silk', 'sing', 'site',
  'size', 'skin', 'slow', 'snow', 'sold', 'some', 'song', 'soon', 'sort', 'soul',
  'soup', 'spot', 'star', 'stay', 'step', 'stop', 'such', 'suit', 'sure', 'take',
  'tale', 'talk', 'tall', 'tank', 'task', 'team', 'tell', 'tend', 'term', 'test',
  'text', 'than', 'that', 'them', 'then', 'they', 'thin', 'this', 'thus', 'tide',
  'time', 'tiny', 'told', 'tone', 'took', 'tool', 'tour', 'town', 'tree', 'trip',
  'true', 'tune', 'turn', 'twin', 'type', 'unit', 'upon', 'used', 'user', 'vast',
  'very', 'view', 'vote', 'wage', 'wait', 'wake', 'walk', 'wall', 'want', 'ward',
  'warm', 'warn', 'wash', 'wave', 'ways', 'weak', 'wear', 'week', 'well', 'went',
  'were', 'west', 'what', 'when', 'whom', 'wide', 'wife', 'wild', 'will', 'wind',
  'wine', 'wing', 'wire', 'wise', 'wish', 'with', 'wood', 'word', 'wore', 'work',
  'yard', 'year', 'your', 'zone',

  // 5-letter
  'about', 'above', 'admit', 'after', 'again', 'agent', 'agree', 'alarm', 'album',
  'alive', 'allow', 'alone', 'along', 'angel', 'anger', 'angle', 'apart', 'apple',
  'apply', 'aside', 'avoid', 'award', 'aware', 'badly', 'basic', 'basis', 'beach',
  'began', 'begin', 'being', 'below', 'birth', 'black', 'blame', 'blank', 'block',
  'blood', 'board', 'bound', 'brain', 'brand', 'bread', 'break', 'brief', 'bring',
  'broad', 'brown', 'build', 'built', 'cabin', 'carry', 'catch', 'cause', 'cells',
  'chair', 'chart', 'cheap', 'check', 'chest', 'chief', 'child', 'china', 'civil',
  'claim', 'class', 'clean', 'clear', 'click', 'climb', 'clock', 'close', 'cloud',
  'coach', 'coast', 'color', 'could', 'count', 'court', 'cover', 'craft', 'crash',
  'cream', 'crime', 'cross', 'crowd', 'crown', 'daily', 'dance', 'death', 'depth',
  'doing', 'doubt', 'dozen', 'draft', 'drama', 'drawn', 'dream', 'dress', 'drink',
  'drive', 'drove', 'eager', 'eight', 'elect', 'enemy', 'enjoy', 'enter', 'entry',
  'equal', 'error', 'event', 'every', 'exact', 'exist', 'extra', 'faith', 'false',
  'fault', 'field', 'fifth', 'fifty', 'fight', 'final', 'first', 'fixed', 'flame',
  'flash', 'fleet', 'floor', 'focus', 'force', 'forty', 'found', 'frame', 'fresh',
  'front', 'fruit', 'fully', 'funny', 'given', 'glass', 'globe', 'going', 'grade',
  'grand', 'grant', 'grass', 'great', 'green', 'group', 'guard', 'guess', 'guest',
  'guide', 'happy', 'heart', 'heavy', 'horse', 'hotel', 'house', 'human', 'humor',
  'image', 'index', 'inner', 'input', 'issue', 'judge', 'known', 'large', 'later',
  'laugh', 'layer', 'learn', 'least', 'leave', 'legal', 'level', 'light', 'limit',
  'lives', 'local', 'logic', 'loose', 'lower', 'lunch', 'magic', 'major', 'maker',
  'match', 'maybe', 'mayor', 'media', 'metal', 'might', 'minor', 'minus', 'mixed',
  'model', 'money', 'month', 'moral', 'mount', 'mouse', 'mouth', 'movie', 'music',
  'needs', 'never', 'newly', 'night', 'noise', 'north', 'noted', 'novel', 'nurse',
  'occur', 'ocean', 'offer', 'often', 'order', 'other', 'outer', 'owner', 'paint',
  'panel', 'paper', 'party', 'peace', 'phase', 'phone', 'photo', 'piece', 'pilot',
  'pitch', 'place', 'plain', 'plane', 'plant', 'plate', 'point', 'pound', 'power',
  'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize', 'proof', 'proud',
  'prove', 'queen', 'quick', 'quiet', 'quite', 'radio', 'raise', 'range', 'rapid',
  'ratio', 'reach', 'ready', 'refer', 'right', 'rival', 'river', 'rough', 'round',
  'route', 'royal', 'rural', 'scale', 'scene', 'scope', 'score', 'sense', 'serve',
  'seven', 'shall', 'shape', 'share', 'sharp', 'sheet', 'shelf', 'shell', 'shift',
  'shirt', 'shock', 'shoot', 'short', 'shown', 'sight', 'since', 'sixth', 'sixty',
  'sized', 'skill', 'sleep', 'slide', 'small', 'smart', 'smile', 'smoke', 'solid',
  'solve', 'sorry', 'sound', 'south', 'space', 'spare', 'speak', 'speed', 'spend',
  'spent', 'spite', 'split', 'spoke', 'sport', 'staff', 'stage', 'stake', 'stand',
  'start', 'state', 'steam', 'steel', 'stick', 'still', 'stock', 'stone', 'stood',
  'store', 'storm', 'story', 'strip', 'study', 'stuff', 'style', 'sugar', 'suite',
  'super', 'sweet', 'table', 'taken', 'taste', 'taxes', 'teach', 'thank', 'theft',
  'their', 'theme', 'there', 'these', 'thick', 'thing', 'think', 'third', 'those',
  'three', 'threw', 'throw', 'tight', 'times', 'tired', 'title', 'today', 'token',
  'topic', 'total', 'touch', 'tough', 'tower', 'track', 'trade', 'train', 'treat',
  'trend', 'trial', 'tribe', 'trick', 'tried', 'troop', 'truck', 'truly', 'trust',
  'truth', 'twice', 'under', 'union', 'unity', 'until', 'upper', 'upset', 'urban',
  'usage', 'usual', 'valid', 'value', 'video', 'visit', 'vital', 'voice', 'waste',
  'watch', 'water', 'wheel', 'where', 'which', 'while', 'white', 'whole', 'whose',
  'woman', 'world', 'worry', 'worse', 'worth', 'would', 'wound', 'write', 'wrong',
  'wrote', 'yield', 'young', 'youth',

  // 6-letter
  'accept', 'access', 'across', 'acting', 'action', 'active', 'actual', 'advice',
  'advise', 'affair', 'affect', 'afford', 'afraid', 'agency', 'agenda', 'almost',
  'always', 'amount', 'animal', 'annual', 'answer', 'anyone', 'anyway', 'appeal',
  'appear', 'around', 'arrive', 'artist', 'aspect', 'assess', 'assist', 'assume',
  'attack', 'attend', 'august', 'author', 'autumn', 'avenue', 'backed', 'barely',
  'basket', 'battle', 'beauty', 'become', 'before', 'behalf', 'behind', 'belief',
  'belong', 'beside', 'better', 'beyond', 'bishop', 'border', 'bottle', 'bottom',
  'bought', 'branch', 'breath', 'bridge', 'bright', 'broken', 'budget', 'burden',
  'bureau', 'button', 'camera', 'cancer', 'cannot', 'carbon', 'career', 'castle',
  'casual', 'caught', 'centre', 'chance', 'change', 'charge', 'choice', 'choose',
  'chosen', 'church', 'circle', 'client', 'closed', 'closer', 'coffee', 'column',
  'combat', 'coming', 'common', 'comply', 'copper', 'corner', 'costly', 'county',
  'couple', 'course', 'covers', 'create', 'credit', 'crisis', 'custom', 'damage',
  'danger', 'dealer', 'debate', 'decade', 'decide', 'defeat', 'defend', 'define',
  'degree', 'demand', 'depend', 'deputy', 'desert', 'design', 'desire', 'detail',
  'detect', 'device', 'differ', 'dinner', 'direct', 'doctor', 'dollar', 'domain',
  'double', 'driven', 'driver', 'during', 'easily', 'eating', 'editor', 'effect',
  'effort', 'eighth', 'either', 'eleven', 'emerge', 'empire', 'employ', 'enable',
  'ending', 'energy', 'engage', 'engine', 'enough', 'ensure', 'entire', 'entity',
  'equity', 'escape', 'estate', 'ethnic', 'expand', 'expect', 'expert', 'export',
  'extend', 'extent', 'fabric', 'facing', 'factor', 'failed', 'fairly', 'family',
  'famous', 'father', 'fellow', 'female', 'figure', 'filing', 'finger', 'finish',
  'fiscal', 'flight', 'flying', 'follow', 'forced', 'forest', 'forget', 'formal',
  'format', 'former', 'foster', 'fought', 'fourth', 'french', 'friend', 'future',
  'garden', 'gather', 'gender', 'global', 'golden', 'ground', 'growth', 'guilty',
  'handle', 'happen', 'hardly', 'headed', 'health', 'heated', 'height', 'hidden',
  'holder', 'honest', 'hoping', 'humble', 'hunter', 'hybrid', 'impact', 'import',
  'income', 'indeed', 'injury', 'insect', 'inside', 'intend', 'intent', 'invest',
  'island', 'itself', 'jersey', 'joined', 'junior', 'killed', 'lately', 'latest',
  'latter', 'launch', 'lawyer', 'leader', 'league', 'legacy', 'length', 'lesson',
  'letter', 'likely', 'linked', 'liquid', 'listen', 'little', 'living', 'lonely',
  'longer', 'losing', 'lovely', 'loving', 'mainly', 'making', 'manage', 'manner',
  'manual', 'margin', 'marine', 'marked', 'market', 'martin', 'master', 'matter',
  'mature', 'medium', 'member', 'memory', 'mental', 'merely', 'method', 'middle',
  'miller', 'mining', 'minute', 'mirror', 'mobile', 'modern', 'modest', 'module',
  'moment', 'morale', 'mostly', 'mother', 'motion', 'moving', 'murder', 'museum',
  'mutual', 'myself', 'narrow', 'nation', 'native', 'nature', 'nearby', 'nearly',
  'newest', 'normal', 'notice', 'notion', 'number', 'object', 'obtain', 'offers',
  'office', 'online', 'opened', 'openly', 'option', 'orange', 'origin', 'output',
  'oxford', 'packed', 'palace', 'parent', 'partly', 'patent', 'people', 'period',
  'permit', 'person', 'phrase', 'picked', 'pillar', 'placed', 'planet', 'player',
  'please', 'plenty', 'pocket', 'police', 'policy', 'porter', 'powder', 'prayer',
  'prefer', 'pretty', 'priest', 'prince', 'prison', 'profit', 'proper', 'proven',
  'public', 'pursue', 'putting', 'racial', 'raised', 'random', 'rarely', 'rather',
  'rating', 'reader', 'really', 'reason', 'recall', 'recent', 'reckon', 'record',
  'redeem', 'reduce', 'reform', 'refuse', 'regard', 'regime', 'region', 'relate',
  'relief', 'remain', 'remark', 'remind', 'remote', 'remove', 'repair', 'repeat',
  'report', 'rescue', 'resort', 'result', 'retail', 'retain', 'return', 'reveal',
  'review', 'reward', 'riding', 'rising', 'robust', 'rolled', 'rubber', 'ruling',
  'sacred', 'safety', 'salary', 'sample', 'saving', 'saying', 'scheme', 'school',
  'screen', 'search', 'season', 'second', 'secret', 'sector', 'secure', 'seeing',
  'seldom', 'select', 'seller', 'senate', 'senior', 'series', 'settle', 'seven',
  'severe', 'sexual', 'should', 'shower', 'signal', 'silent', 'silver', 'simple',
  'simply', 'single', 'sister', 'sleeve', 'slight', 'slowly', 'sniper', 'soccer',
  'social', 'sodium', 'softly', 'solely', 'solved', 'sought', 'source', 'speech',
  'spirit', 'spoken', 'spread', 'spring', 'square', 'stable', 'stages', 'stairs',
  'stance', 'static', 'status', 'steady', 'steam', 'stolen', 'strain', 'stream',
  'street', 'stress', 'strict', 'strike', 'string', 'stripe', 'strong', 'struck',
  'studio', 'submit', 'sudden', 'suffer', 'summer', 'summit', 'supply', 'surely',
  'survey', 'switch', 'symbol', 'system', 'taking', 'talent', 'target', 'taught',
  'tender', 'tennis', 'thanks', 'theory', 'thirty', 'though', 'threat', 'thrown',
  'ticket', 'timely', 'timing', 'tissue', 'toilet', 'tomato', 'tongue', 'toward',
  'travel', 'treaty', 'trying', 'tunnel', 'twelve', 'twenty', 'unable', 'unfair',
  'unique', 'united', 'unless', 'unlike', 'update', 'useful', 'valley', 'varied',
  'vendor', 'versus', 'victim', 'virtue', 'vision', 'visual', 'volume', 'walker',
  'wealth', 'weapon', 'weekly', 'weight', 'window', 'winner', 'winter', 'within',
  'wonder', 'wooden', 'worker', 'wright', 'writer', 'yellow',
];
