// AUTO-GENERATED by scripts/gen-lessons-cjs.mjs — DO NOT EDIT BY HAND.
// Source of truth: src/lib/lessons.ts + src/lib/data.ts (CHALLENGES).
// Regenerated on every `npm run build`.

export const LESSONS = [
  {
    "id": "lesson-1",
    "title": "Chapter 1: The F and J Keys",
    "subtitle": "Focus: Index fingers",
    "instructions": "Place your left index finger on F and right index finger on J. Feel the bumps!",
    "keys": "fj",
    "guide": [
      "Welcome. This is the most important chapter of the entire curriculum — everything else builds on this foundation.",
      "Look at the F and J keys on your keyboard. Notice the tiny raised bumps on each one. Those bumps exist for one reason: so your fingers can find the home row without looking. Place your LEFT INDEX FINGER on F and your RIGHT INDEX FINGER on J. Let your other fingers rest naturally on the keys beside them.",
      "For this chapter, you only need two fingers. Keep your eyes on the screen, not your hands. If you make mistakes — and you will — that is fine. Speed comes later. Accuracy now."
    ],
    "tip": "If you feel the urge to look at your hands, resist it. The whole point is to build a map in your fingers, not your eyes."
  },
  {
    "id": "lesson-2",
    "title": "Chapter 2: Adding Space",
    "subtitle": "Focus: Thumbs",
    "instructions": "Use your thumb to press the space bar between sequences.",
    "keys": "fj ",
    "guide": [
      "Both thumbs sit naturally on the space bar. Most touch-typists use whichever thumb is more comfortable — there is no \"correct\" thumb for space.",
      "Pick one thumb (most right-handed people pick the right) and commit to it. The space bar is the most-pressed key on any keyboard. Hitting it consistently with the same thumb makes you faster.",
      "Continue keeping your eyes on the screen. The rhythm you want is: tap, tap, tap, SPACE, tap, tap, tap, SPACE."
    ],
    "tip": "Space is your reset key. Every space is a fresh start — a tiny moment to settle your fingers back on F and J."
  },
  {
    "id": "lesson-3",
    "title": "Chapter 3: D and K Keys",
    "subtitle": "Focus: Middle fingers",
    "instructions": "Use your left middle finger for D and right middle finger for K.",
    "keys": "dfjk ",
    "guide": [
      "Now we add the MIDDLE fingers. D belongs to the left middle, K belongs to the right middle.",
      "Keep your index fingers anchored on F and J. The middle fingers should reach naturally to D and K without your hand moving. If your hand drifts, reset.",
      "This chapter is about controlled isolation: only the middle fingers move. Index fingers stay put."
    ],
    "tip": ""
  },
  {
    "id": "lesson-4",
    "title": "Chapter 4: S and L Keys",
    "subtitle": "Focus: Ring fingers",
    "instructions": "Use your left ring finger for S and right ring finger for L.",
    "keys": "sdflkj ",
    "guide": [
      "Ring fingers are the weakest fingers on most people's hands. Be patient with them.",
      "S goes to the left ring finger. L goes to the right ring finger. They should reach without the rest of your hand moving — the index and middle fingers stay anchored.",
      "You may notice the ring finger wants to pull other fingers along with it. That is normal. With practice the fingers learn to operate independently."
    ],
    "tip": "Slow down on this chapter. Ring-finger accuracy is the difference between 60 WPM and 100 WPM later."
  },
  {
    "id": "lesson-5",
    "title": "Chapter 5: A and ; Keys",
    "subtitle": "Focus: Pinky fingers",
    "instructions": "Use your left pinky for A and right pinky for Semicolon (;).",
    "keys": "asdfjkl; ",
    "guide": [
      "The pinkies! The smallest, weakest, most independent of the fingers. They also do the most work in real-world typing — every Shift, Enter, Tab, and Backspace runs through a pinky.",
      "Left pinky on A. Right pinky on the semicolon (;). Your hand should now span the full home row: A S D F · J K L ;",
      "Take this chapter slow. Pinky-key accuracy is what separates intermediate typists from professionals."
    ],
    "tip": "Curl your pinkies slightly. A flat pinky tends to slap multiple keys. A curled pinky lands clean."
  },
  {
    "id": "lesson-6",
    "title": "Chapter 6: Home Row Words",
    "subtitle": "Focus: Muscle memory",
    "instructions": "Now let us combine all the home row keys into real words!",
    "keys": "asdfjkl; ",
    "guide": [
      "You now control the entire home row. Time to type actual English words.",
      "Notice how the home row alone makes a surprising number of useful words: ASK, DAD, SAD, LAD, ADD, SALAD, FALL, FLASK, GLASS.",
      "For this chapter, every key your fingers need is already under your fingers. There is no excuse to look at the keyboard. Trust the bumps on F and J. They will guide you home every time."
    ],
    "tip": ""
  },
  {
    "id": "lesson-7",
    "title": "Chapter 7: G and H Keys",
    "subtitle": "Focus: Index extensions",
    "instructions": "Stretch your left index to G and right index to H. Return to F and J immediately.",
    "keys": "fghj ",
    "guide": [
      "Your index fingers are the most flexible — they cover an EXTRA column each. The left index reaches IN to G, the right index reaches IN to H.",
      "The critical word here is \"return\". After tapping G, the left index snaps back to F. After tapping H, the right index snaps back to J. Never let your hand drift.",
      "This snap-back motion is what keeps your typing fast. Anchored hands type fast. Drifting hands type slow."
    ],
    "tip": "Whisper \"F-J-F-J\" between drills. It re-anchors your hands without you having to look."
  },
  {
    "id": "lesson-8",
    "title": "Chapter 8: Home Row Sentences",
    "subtitle": "Focus: End of Foundations",
    "instructions": "Mix everything you learned into smooth home-row sentences.",
    "keys": "asdfghjkl; ",
    "guide": [
      "Congratulations — you now own the home row. This chapter is a victory lap.",
      "Type these mini-sentences smoothly, without stopping between words. The goal is RHYTHM. A steady metronome of keystrokes is more valuable than sporadic speed.",
      "After this chapter, the next eight lessons add the top row — R, U, E, I, T, Y, W, O, Q, P. The home row will still be your base of operations. Always return."
    ],
    "tip": ""
  },
  {
    "id": "lesson-9",
    "title": "Chapter 9: R and U Keys",
    "subtitle": "Focus: Upward index extensions",
    "instructions": "Reach up with your left index to R, and right index to U.",
    "keys": "frju ",
    "guide": [
      "The top row starts here. R sits directly above F — left index moves UP and slightly forward. U sits directly above J — right index moves UP and slightly forward.",
      "Notice the geometry: every top-row letter is reached from the home-row finger immediately below it. You already know which finger to use; you just have to teach it to reach.",
      "Snap back to F and J after every top-row tap. The home row is your anchor."
    ],
    "tip": ""
  },
  {
    "id": "lesson-10",
    "title": "Chapter 10: E and I Keys",
    "subtitle": "Focus: Upward middle extensions",
    "instructions": "Reach up with your left middle to E, and right middle to I.",
    "keys": "dekie ",
    "guide": [
      "E sits above D — use your left middle finger. I sits above K — use your right middle finger.",
      "E and I are the two most common vowels in English. Mastering these alone will speed up almost everything you type.",
      "You now know enough of the alphabet to type real words: DRIVE, FRIED, IDEA, FIRE. Try them."
    ],
    "tip": "When E and I appear back-to-back (FIELD, RELIEVE), it tests your hand independence. Slow down for accuracy."
  },
  {
    "id": "lesson-11",
    "title": "Chapter 11: T and Y Keys",
    "subtitle": "Focus: Stretched index reaches",
    "instructions": "Left index reaches diagonally up-left to T. Right index reaches up-right to Y.",
    "keys": "fghjty ",
    "guide": [
      "T and Y are the trickiest letters on the top row. The index fingers have to stretch FARTHER — T is up and toward the center, Y is up and toward the center too.",
      "Your hand may want to lift. Resist. Keep the other fingers anchored. Only the index stretches.",
      "T is the second most common letter in English (after E). This chapter pays off immediately."
    ],
    "tip": ""
  },
  {
    "id": "lesson-12",
    "title": "Chapter 12: W and O Keys",
    "subtitle": "Focus: Ring fingers reach up",
    "instructions": "Left ring finger up to W. Right ring finger up to O.",
    "keys": "swlo ",
    "guide": [
      "W sits above S (left ring). O sits above L (right ring). Ring fingers, again — patience.",
      "Common words now within reach: WORD, WORK, ROW, LOW, FLOW, WORLD, GOOD. Notice how vowel-rich English really is.",
      "If your ring finger drags the pinky along with it, that is a hand-independence issue. Slow down and isolate."
    ],
    "tip": ""
  },
  {
    "id": "lesson-13",
    "title": "Chapter 13: Q and P Keys",
    "subtitle": "Focus: Pinky reaches up",
    "instructions": "Left pinky up to Q. Right pinky up to P.",
    "keys": "aq;p ",
    "guide": [
      "The top corners — Q and P — are reached by the pinkies. These are the longest reaches on the entire keyboard.",
      "Most English words don't have a Q. When one shows up (QUICK, QUIET), the U almost always follows — your right index handles that smoothly.",
      "P is far more common (PLAY, POP, PEOPLE). Train the right pinky to reach without the hand lifting."
    ],
    "tip": ""
  },
  {
    "id": "lesson-14",
    "title": "Chapter 14: Top Row Sentences",
    "subtitle": "End of top-row track",
    "instructions": "Real English sentences using only the keys you know.",
    "keys": "qwertyuiopasdfghjkl; ",
    "guide": [
      "You now control the top row AND the home row. That covers 26 alphabet keys − 7 bottom-row keys = enough to type the majority of English text.",
      "Time for real sentences with rhythm. Don't stop mid-word. Don't look down. Trust your fingers.",
      "After this chapter we drop to the bottom row: V, N, C, M, X, comma, Z, period, B, slash."
    ],
    "tip": ""
  },
  {
    "id": "lesson-15",
    "title": "Chapter 15: V and N Keys",
    "subtitle": "Focus: Bottom index extensions",
    "instructions": "Left index DOWN to V. Right index DOWN to N.",
    "keys": "fvjn ",
    "guide": [
      "Bottom row begins. The index fingers now reach DOWN as well as up.",
      "V is below F — left index curls down and slightly inward. N is below J — right index does the same on the right.",
      "The downward motion uses different muscles than the upward motion. Take your time."
    ],
    "tip": ""
  },
  {
    "id": "lesson-16",
    "title": "Chapter 16: C and M Keys",
    "subtitle": "Focus: Bottom middle extensions",
    "instructions": "Left middle DOWN to C. Right middle DOWN to M.",
    "keys": "dcmk ",
    "guide": [
      "C is below D (left middle). M is below K (right middle).",
      "Both letters are common in English (CAT, CASE, MAY, MAKE). Quick muscle memory pays off here.",
      "Watch for finger drift on M — it likes to recruit the index. Keep the index anchored on J."
    ],
    "tip": ""
  },
  {
    "id": "lesson-17",
    "title": "Chapter 17: X and , Keys",
    "subtitle": "Focus: Bottom ring extensions",
    "instructions": "Left ring DOWN to X. Right ring DOWN to comma (,).",
    "keys": "sx,l ",
    "guide": [
      "X is below S (left ring). Comma is below L (right ring).",
      "Comma is one of the most-used keys in real writing. Treating it as a \"letter\" pays off — punctuation slows down most beginners far more than uncommon letters do."
    ],
    "tip": ""
  },
  {
    "id": "lesson-18",
    "title": "Chapter 18: Z and . Keys",
    "subtitle": "Focus: Bottom pinky extensions",
    "instructions": "Left pinky DOWN to Z. Right pinky DOWN to period (.)",
    "keys": "az;. ",
    "guide": [
      "Z is below A (left pinky). Period is below ; (right pinky).",
      "Z barely appears in English. Period appears constantly. Spend more time on the period.",
      "After this chapter, B and / round out the bottom row."
    ],
    "tip": ""
  },
  {
    "id": "lesson-19",
    "title": "Chapter 19: B and / Keys",
    "subtitle": "Focus: Center-bottom reaches",
    "instructions": "Left index DOWN-IN to B. Right pinky DOWN to / (and ?).",
    "keys": "fb;/ ",
    "guide": [
      "B is the awkward letter. It sits below the gap between G and H — and convention says the LEFT INDEX handles it. So your left index has to stretch down and inward.",
      "The slash key (/) sits to the right of period — right pinky territory. Shift+/ gives you ?.",
      "After this chapter you have typed every letter of the alphabet. The whole keyboard is yours."
    ],
    "tip": ""
  },
  {
    "id": "lesson-20",
    "title": "Chapter 20: Full Alphabet Sentences",
    "subtitle": "End of bottom-row track",
    "instructions": "Pangrams — sentences using every letter of the alphabet.",
    "keys": "abcdefghijklmnopqrstuvwxyz, .",
    "guide": [
      "You have now drilled every letter of the alphabet. Time to prove it with pangrams — short sentences that contain every letter at least once.",
      "These are classic typing-practice sentences. Type them smoothly and you have mastered the keyboard's alphabetic core.",
      "Next track: Shift + capitals."
    ],
    "tip": ""
  },
  {
    "id": "lesson-21",
    "title": "Chapter 21: Left Shift",
    "subtitle": "Focus: Right-hand letters with Shift",
    "instructions": "Use the LEFT Shift key (held by left pinky) for right-hand capitals.",
    "keys": "asdfghjkl;",
    "guide": [
      "Shift comes in pairs — left Shift and right Shift. The rule is simple: use the OPPOSITE shift from the letter you are capitalizing.",
      "For RIGHT-hand letters (Y, U, I, O, P, H, J, K, L, N, M), press LEFT Shift with your left pinky and type the letter with the right hand.",
      "The shift goes DOWN with the pinky and STAYS DOWN until the capital letter is typed. Release together."
    ],
    "tip": "Left pinky holds Shift while left hand stays anchored on A. The right hand types the letter. Two hands, two roles."
  },
  {
    "id": "lesson-22",
    "title": "Chapter 22: Right Shift",
    "subtitle": "Focus: Left-hand letters with Shift",
    "instructions": "Use the RIGHT Shift key (held by right pinky) for left-hand capitals.",
    "keys": "asdfghjkl;",
    "guide": [
      "For LEFT-hand letters (Q, W, E, R, T, A, S, D, F, G, Z, X, C, V, B), press RIGHT Shift with your right pinky.",
      "Same mechanics — shift down, letter typed, shift released.",
      "It feels awkward at first. The investment pays off massively. Shift-on-the-wrong-side typists max out around 50 WPM. Shift-on-the-correct-side typists pass 100 WPM easily."
    ],
    "tip": ""
  },
  {
    "id": "lesson-23",
    "title": "Chapter 23: Proper Nouns & Names",
    "subtitle": "Focus: Capital + lowercase mix",
    "instructions": "Real names, real cities, real proper nouns.",
    "keys": "qwertyuiopasdfghjkl;zxcvbnm, .",
    "guide": [
      "Now the shift dance gets real. Every name, every place, every brand starts with a capital and continues lowercase.",
      "The pattern: shift down, capital letter, shift up, lowercase letters. Smoothly.",
      "These prompts are intentionally short — focus on the shift-letter-release rhythm."
    ],
    "tip": ""
  },
  {
    "id": "lesson-24",
    "title": "Chapter 24: Number Row Center (4 5 6 7)",
    "subtitle": "Focus: Index fingers reach for digits",
    "instructions": "Both index fingers stretch UP TWO ROWS for the center digits.",
    "keys": "45 67 fjghr u",
    "guide": [
      "The number row is two rows above home. Your fingers need to actually TRAVEL there, then snap back.",
      "Left index handles 4 and 5. Right index handles 6 and 7. Notice each index covers TWO digits (its natural column + one inward).",
      "Going to the number row and looking is fine for the first few attempts. Force yourself to do it by feel by the end of the chapter."
    ],
    "tip": "Many keyboards have a \"5\" that's the visual midpoint. Train your fingers to feel where 5/6 split."
  },
  {
    "id": "lesson-25",
    "title": "Chapter 25: Number Row Edges (1 2 3 8 9 0)",
    "subtitle": "Focus: Outer fingers for outer digits",
    "instructions": "Left hand handles 1-3, right hand handles 8-0.",
    "keys": "1234567890 ",
    "guide": [
      "The outer digits each get their own finger: 1=pinky, 2=ring, 3=middle (left hand). 8=middle, 9=ring, 0=pinky (right hand).",
      "These are LONG reaches, especially for the pinkies. Curl the pinky and go.",
      "Combined with chapter 24, you now own the entire number row."
    ],
    "tip": ""
  },
  {
    "id": "lesson-26",
    "title": "Chapter 26: Common Punctuation",
    "subtitle": "Focus: . , ; ' \" : ?",
    "instructions": "The punctuation that appears in real writing every day.",
    "keys": "asdfjkl;', .?",
    "guide": [
      "Real writing is 80% letters, 20% punctuation. Most beginners learn the letters and ignore the punctuation. That cap their speed forever.",
      "Period and comma you already know (chapters 17-18). Add: semicolon (right pinky, home row), apostrophe (right pinky, one right of semicolon), quote (Shift+apostrophe), colon (Shift+semicolon).",
      "Question mark is Shift + /. We did / in chapter 19."
    ],
    "tip": ""
  },
  {
    "id": "lesson-27",
    "title": "Chapter 27: Brackets and Math",
    "subtitle": "Focus: ( ) [ ] { } + - = /",
    "instructions": "Symbols every programmer and most writers need.",
    "keys": "[]()+-=/ ",
    "guide": [
      "These are the symbols that don't appear in regular prose but appear constantly in code, math, lists, and structured writing.",
      "Parentheses: Shift+9 = ( and Shift+0 = ). Brackets: [ and ] are unshifted, right pinky. Braces: Shift+[ = { and Shift+] = }.",
      "Plus, minus, equals, slash are all single-finger reaches in the top-right and bottom-right."
    ],
    "tip": ""
  },
  {
    "id": "lesson-28",
    "title": "Chapter 28: Common Bigrams",
    "subtitle": "Focus: Letter pairs that show up everywhere",
    "instructions": "TH, HE, IN, ER, AN, RE, ON, AT, EN, ND — the most common two-letter sequences in English.",
    "keys": "abcdefghijklmnopqrstuvwxyz ",
    "guide": [
      "Real speed comes from CHUNKING. Fast typists don't type one letter at a time — they type in pairs, syllables, even whole short words.",
      "These ten bigrams account for roughly 25% of all letter pairs in English text. Drill them until your fingers fire them as a single motion.",
      "Don't think \"T then H\". Think \"TH\". One unit."
    ],
    "tip": "When TH fires as a single muscle memory, your WPM jumps overnight."
  },
  {
    "id": "lesson-29",
    "title": "Chapter 29: Common Trigrams",
    "subtitle": "Focus: Three-letter chunks",
    "instructions": "THE, AND, ING, ION, TIO, ENT, ATI, FOR, HER, TER — three-letter combos that are everywhere.",
    "keys": "abcdefghijklmnopqrstuvwxyz ",
    "guide": [
      "After bigrams come trigrams. THE alone is roughly 6% of all words in English. ING ends millions of verbs.",
      "Each trigram should feel like a single keystroke once mastered."
    ],
    "tip": ""
  },
  {
    "id": "lesson-30",
    "title": "Chapter 30: 100 Most Common Words",
    "subtitle": "Focus: Word fluency",
    "instructions": "The 100 most-used words in English. Master these and you can type 50%+ of any text.",
    "keys": "abcdefghijklmnopqrstuvwxyz ",
    "guide": [
      "Linguists have shown that just 100 words account for about half of all words in spoken and written English.",
      "When THE, OF, AND, A, TO, IN, IS, YOU, THAT, IT — and 90 similar words — fire as automatic muscle patterns, your real-world WPM doubles.",
      "These prompts mix and match the top 100. Type them smoothly and don't stop between words."
    ],
    "tip": ""
  },
  {
    "id": "lesson-31",
    "title": "Chapter 31: Sentence Rhythm",
    "subtitle": "Focus: Punctuation cues",
    "instructions": "Smooth sentences with all the punctuation that real writing uses.",
    "keys": "abcdefghijklmnopqrstuvwxyz ,.;':\"?-",
    "guide": [
      "Real prose has commas, periods, semicolons, quotation marks, and apostrophes scattered throughout. The shift-and-symbol dance becomes part of your rhythm.",
      "Don't slow down for punctuation. Type it AS you type the words around it. The comma after a word is part of that word's rhythm, not a separate event."
    ],
    "tip": "A great test: can you type a comma without your eyes flicking to your hands? If yes, you've nailed it."
  },
  {
    "id": "lesson-32",
    "title": "Chapter 32: Code Typing Micro-Drill",
    "subtitle": "Focus: Real syntactical code",
    "instructions": "JavaScript and Python snippets — brackets, semicolons, operators all in motion.",
    "keys": "abcdefghijklmnopqrstuvwxyz0123456789 ()[]{}+-=/<>;:'\".,",
    "guide": [
      "The final chapter. Code looks intimidating but is mostly the same characters as English, just arranged differently.",
      "Programmers who can't touch-type lose hours every day. The investment in this chapter pays off forever — every line of code you write for the rest of your career runs through these muscles.",
      "After this, the curriculum is done. Keep practicing daily — even 10 minutes a day will keep your speed climbing."
    ],
    "tip": "There is no finish line. The best typists in the world still practice. Welcome to the club."
  },
  {
    "id": "lesson-33",
    "title": "Chapter 33: Double Letters",
    "subtitle": "Focus: Same-finger repeats",
    "instructions": "Words with doubled letters — LL, SS, EE, OO, TT — train the quick same-finger tap.",
    "keys": "abcdefghijklmnopqrstuvwxyz ",
    "guide": [
      "Doubled letters are a hidden speed trap. Hitting the SAME key twice, fast and clean, uses a different motion than alternating fingers — a quick double-tap, not two separate presses.",
      "Watch for the weak fingers especially: the double-L (LL), double-S (SS), and double-O (OO) all land on ring and pinky fingers that like to be lazy.",
      "Keep the rhythm even. A doubled letter should sound like one confident \"tut-tut\", not a hesitant \"tap … tap\"."
    ],
    "tip": "If a doubled letter ever produces just one character, you are releasing too slowly. Lift and re-press crisply."
  },
  {
    "id": "lesson-34",
    "title": "Chapter 34: Everyday Words",
    "subtitle": "Focus: Conversational vocabulary",
    "instructions": "The words you actually use in messages, emails, and notes every day.",
    "keys": "abcdefghijklmnopqrstuvwxyz ",
    "guide": [
      "Beyond the top-100 function words lie the everyday content words — the verbs and nouns of real life. These are what you type when you write to a friend or fire off an email.",
      "Type these in smooth phrases. Your goal is to stop seeing individual letters and start seeing whole words flow from your fingertips.",
      "Aim for an even cadence. Consistency beats bursts of speed followed by long pauses."
    ],
    "tip": ""
  },
  {
    "id": "lesson-35",
    "title": "Chapter 35: Capitalization in Context",
    "subtitle": "Focus: Sentences that start with capitals",
    "instructions": "Full sentences — each begins with a capital and ends with punctuation.",
    "keys": "abcdefghijklmnopqrstuvwxyz ,.",
    "guide": [
      "Real writing capitalizes the first letter of every sentence. That means a Shift press at the start of almost every line, woven seamlessly into your rhythm.",
      "The pattern from Track 4 returns: opposite-hand Shift, capital, release, lowercase. Now you do it mid-flow, without stopping.",
      "Read each sentence once, then type it as one continuous motion. The capital at the start should not slow you down at all."
    ],
    "tip": "The full stop and the next capital are a pair. Train them as a single beat: \". \" then Shift — period, space, capital."
  },
  {
    "id": "lesson-36",
    "title": "Chapter 36: Numbers in the Wild",
    "subtitle": "Focus: Digits inside real text",
    "instructions": "Dates, prices, times, and quantities — numbers mixed with words.",
    "keys": "abcdefghijklmnopqrstuvwxyz0123456789 ,.:$",
    "guide": [
      "In real writing, numbers rarely appear alone. They sit inside sentences: a price, a date, a time, a count. Your fingers must travel to the number row and back without losing the thread of the words.",
      "This is the true test of the number row from Track 5. Letters, then a reach up for digits, then back to letters — smoothly.",
      "Don't look down for the digits. You drilled them; trust them."
    ],
    "tip": ""
  },
  {
    "id": "lesson-37",
    "title": "Chapter 37: Symbols & Email",
    "subtitle": "Focus: @ # & % and the symbol shift",
    "instructions": "The symbols of modern life — emails, hashtags, percentages, and handles.",
    "keys": "abcdefghijklmnopqrstuvwxyz0123456789 @#&%.",
    "guide": [
      "The @ sign (Shift+2), the hashtag # (Shift+3), the ampersand & (Shift+7), and the percent % (Shift+5) are everywhere online. Each is a Shift + number-row reach.",
      "These combine a Shift hold with a long reach to the number row — the hardest two-hand coordination so far. Go slowly until it clicks.",
      "Type the handles and addresses below as single units. Notice how your hands learn the shape of an email address."
    ],
    "tip": "For Shift+symbol on the number row, use the OPPOSITE-hand Shift, just like capitals. @ is left of center, so use the right Shift."
  },
  {
    "id": "lesson-38",
    "title": "Chapter 38: Longer Words",
    "subtitle": "Focus: Multi-syllable stamina",
    "instructions": "Bigger words that test finger endurance and accuracy over distance.",
    "keys": "abcdefghijklmnopqrstuvwxyz ",
    "guide": [
      "Short words are sprints; long words are middle-distance runs. A ten-letter word is ten chances to make a mistake, so accuracy under sustained motion is the skill here.",
      "Break each long word into the chunks you trained in Track 6 — syllables and common trigrams (ING, TION, MENT). Your fingers already know the pieces.",
      "If you stumble, slow down. A clean slow run trains the right pattern; a fast messy run trains the wrong one."
    ],
    "tip": ""
  },
  {
    "id": "lesson-39",
    "title": "Chapter 39: Quotes & Wisdom",
    "subtitle": "Focus: Flowing real prose",
    "instructions": "Famous quotations — type them as smooth, meaningful sentences.",
    "keys": "abcdefghijklmnopqrstuvwxyz ,.'-",
    "guide": [
      "Now you type real, complete thoughts. Quotations carry natural rhythm and varied punctuation — the perfect material for building genuine fluency.",
      "Read each quote, understand it, then type it as one flowing line. Meaning helps memory; when you understand the words, your fingers predict them.",
      "This is what all the drills were for: typing real language without thinking about the keyboard at all."
    ],
    "tip": "Let your eyes read slightly AHEAD of your fingers — a word or two ahead. That look-ahead is the secret of every fast typist."
  },
  {
    "id": "lesson-40",
    "title": "Chapter 40: The Final Sprint",
    "subtitle": "Focus: Everything, at speed",
    "instructions": "Mixed prose with capitals, numbers, and punctuation — the graduation drill.",
    "keys": "abcdefghijklmnopqrstuvwxyz0123456789 ,.:;'\"!?-",
    "guide": [
      "The last chapter. Everything you have learned — letters, capitals, numbers, symbols, punctuation, rhythm, and look-ahead — comes together here.",
      "These sentences hold a bit of everything. Type them the way you would write a real message: confidently, smoothly, eyes forward, fingers trusting the map you spent 40 chapters building.",
      "When you can type these cleanly at a steady pace, you are no longer learning to type — you are simply typing. That was the whole goal."
    ],
    "tip": "Set a timer mode and chase your own record. The curriculum ends, but the practice never has to. Welcome to fluency."
  }
];

export const CHALLENGES = [
  {
    "id": "daily-challenge",
    "label": "Daily Challenge",
    "desc": "Today's seeded run · resets at midnight"
  },
  {
    "id": "speed-run",
    "label": "Speed Run Endurance",
    "desc": "Real English paragraphs testing muscle stamina."
  },
  {
    "id": "expert-sentences",
    "label": "Punctuation Expert",
    "desc": "Complex sentences with quotes, brackets, and syntax."
  },
  {
    "id": "code-sprint",
    "label": "Code Syntax Sprint",
    "desc": "Real syntactical coding layouts in JS/Python."
  }
];
