// Re-export the lesson/challenge data in a build-script-friendly form.
// We keep it in plain ESM (no TS) so the SEO script can `import` it via Node
// without a transpile step.
//
// IMPORTANT: keep this in sync with ../src/lib/lessons.ts and
// ../src/lib/data.ts → CHALLENGES. The single point of truth for the app
// itself is still the TypeScript files; this is the build-step mirror.

export const LESSONS = [
  { id: 'lesson-1',  title: 'Chapter 1: The F and J Keys',         subtitle: 'Focus: Index fingers',                instructions: 'Place your left index finger on F and right index finger on J. Feel the bumps!',                                                                                          keys: 'fj',         tip: '' },
  { id: 'lesson-2',  title: 'Chapter 2: Adding Space',             subtitle: 'Focus: Thumbs',                       instructions: 'Use your thumb to press the space bar between sequences.',                                                                                                                  keys: 'fj ',        tip: '' },
  { id: 'lesson-3',  title: 'Chapter 3: D and K Keys',             subtitle: 'Focus: Middle fingers',               instructions: 'Use your left middle finger for D and right middle finger for K.',                                                                                                          keys: 'dfjk ',      tip: '' },
  { id: 'lesson-4',  title: 'Chapter 4: S and L Keys',             subtitle: 'Focus: Ring fingers',                 instructions: 'Use your left ring finger for S and right ring finger for L.',                                                                                                              keys: 'sdflkj ',    tip: '' },
  { id: 'lesson-5',  title: 'Chapter 5: A and ; Keys',             subtitle: 'Focus: Pinky fingers',                instructions: 'Use your left pinky for A and right pinky for Semicolon (;).',                                                                                                              keys: 'asdfjkl; ',  tip: '' },
  { id: 'lesson-6',  title: 'Chapter 6: Home Row Words',           subtitle: 'Focus: Muscle memory',                instructions: 'Now let us combine all the home row keys into real words!',                                                                                                                 keys: 'asdfjkl; ',  tip: '' },
  { id: 'lesson-7',  title: 'Chapter 7: G and H Keys',             subtitle: 'Focus: Index extensions',             instructions: 'Stretch your left index to G and right index to H. Return to F and J immediately.',                                                                                         keys: 'fghj ',      tip: '' },
  { id: 'lesson-8',  title: 'Chapter 8: Home Row Sentences',       subtitle: 'Focus: End of Foundations',           instructions: 'Mix everything you learned into smooth home-row sentences.',                                                                                                                keys: 'asdfghjkl; ',tip: '' },
  { id: 'lesson-9',  title: 'Chapter 9: R and U Keys',             subtitle: 'Focus: Upward index extensions',      instructions: 'Reach up with your left index to R, and right index to U.',                                                                                                                 keys: 'frju ',      tip: '' },
  { id: 'lesson-10', title: 'Chapter 10: E and I Keys',            subtitle: 'Focus: Upward middle extensions',     instructions: 'Reach up with your left middle to E, and right middle to I.',                                                                                                               keys: 'dekie ',     tip: '' },
  { id: 'lesson-11', title: 'Chapter 11: T and Y Keys',            subtitle: 'Focus: Stretched index reaches',      instructions: 'Left index reaches diagonally up-left to T. Right index reaches up-right to Y.',                                                                                            keys: 'fghjty ',    tip: '' },
  { id: 'lesson-12', title: 'Chapter 12: W and O Keys',            subtitle: 'Focus: Ring fingers reach up',        instructions: 'Left ring finger up to W. Right ring finger up to O.',                                                                                                                      keys: 'swlo ',      tip: '' },
  { id: 'lesson-13', title: 'Chapter 13: Q and P Keys',            subtitle: 'Focus: Pinky reaches up',             instructions: 'Left pinky up to Q. Right pinky up to P.',                                                                                                                                  keys: 'aq;p ',      tip: '' },
  { id: 'lesson-14', title: 'Chapter 14: Top Row Sentences',       subtitle: 'End of top-row track',                instructions: 'Real English sentences using only the keys you know.',                                                                                                                      keys: 'qwertyuiopasdfghjkl; ', tip: '' },
  { id: 'lesson-15', title: 'Chapter 15: V and N Keys',            subtitle: 'Focus: Bottom index extensions',      instructions: 'Left index DOWN to V. Right index DOWN to N.',                                                                                                                              keys: 'fvjn ',      tip: '' },
  { id: 'lesson-16', title: 'Chapter 16: C and M Keys',            subtitle: 'Focus: Bottom middle extensions',     instructions: 'Left middle DOWN to C. Right middle DOWN to M.',                                                                                                                            keys: 'dcmk ',      tip: '' },
  { id: 'lesson-17', title: 'Chapter 17: X and , Keys',            subtitle: 'Focus: Bottom ring extensions',       instructions: 'Left ring DOWN to X. Right ring DOWN to comma (,).',                                                                                                                        keys: 'sx,l ',      tip: '' },
  { id: 'lesson-18', title: 'Chapter 18: Z and . Keys',            subtitle: 'Focus: Bottom pinky extensions',      instructions: 'Left pinky DOWN to Z. Right pinky DOWN to period (.)',                                                                                                                      keys: 'az;. ',      tip: '' },
  { id: 'lesson-19', title: 'Chapter 19: B and / Keys',            subtitle: 'Focus: Center-bottom reaches',        instructions: 'Left index DOWN-IN to B. Right pinky DOWN to / (and ?).',                                                                                                                   keys: 'fb;/ ',      tip: '' },
  { id: 'lesson-20', title: 'Chapter 20: Full Alphabet Sentences', subtitle: 'End of bottom-row track',             instructions: 'Pangrams — sentences using every letter of the alphabet.',                                                                                                                  keys: 'abcdefghijklmnopqrstuvwxyz, .', tip: '' },
  { id: 'lesson-21', title: 'Chapter 21: Left Shift',              subtitle: 'Focus: Right-hand letters with Shift',instructions: 'Use the LEFT Shift key (held by left pinky) for right-hand capitals.',                                                                                                      keys: 'asdfghjkl;',tip: '' },
  { id: 'lesson-22', title: 'Chapter 22: Right Shift',             subtitle: 'Focus: Left-hand letters with Shift', instructions: 'Use the RIGHT Shift key (held by right pinky) for left-hand capitals.',                                                                                                     keys: 'asdfghjkl;',tip: '' },
  { id: 'lesson-23', title: 'Chapter 23: Proper Nouns & Names',    subtitle: 'Focus: Capital + lowercase mix',      instructions: 'Real names, real cities, real proper nouns.',                                                                                                                               keys: 'qwertyuiopasdfghjkl;zxcvbnm, .', tip: '' },
  { id: 'lesson-24', title: 'Chapter 24: Number Row Center (4 5 6 7)', subtitle: 'Focus: Index fingers reach for digits', instructions: 'Both index fingers stretch UP TWO ROWS for the center digits.',                                                                                                       keys: '45 67 fjghr u', tip: '' },
  { id: 'lesson-25', title: 'Chapter 25: Number Row Edges (1 2 3 8 9 0)', subtitle: 'Focus: Outer fingers for outer digits', instructions: 'Left hand handles 1-3, right hand handles 8-0.',                                                                                                                    keys: '1234567890 ', tip: '' },
  { id: 'lesson-26', title: 'Chapter 26: Common Punctuation',      subtitle: "Focus: . , ; ' \" : ?",               instructions: 'The punctuation that appears in real writing every day.',                                                                                                                   keys: "asdfjkl;', .?", tip: '' },
  { id: 'lesson-27', title: 'Chapter 27: Brackets and Math',       subtitle: 'Focus: ( ) [ ] { } + - = /',          instructions: 'Symbols every programmer and most writers need.',                                                                                                                           keys: '[]()+-=/ ',  tip: '' },
  { id: 'lesson-28', title: 'Chapter 28: Common Bigrams',          subtitle: 'Focus: Letter pairs that show up everywhere', instructions: 'TH, HE, IN, ER, AN, RE, ON, AT, EN, ND — the most common two-letter sequences in English.',                                                                          keys: 'abcdefghijklmnopqrstuvwxyz ', tip: '' },
  { id: 'lesson-29', title: 'Chapter 29: Common Trigrams',         subtitle: 'Focus: Three-letter chunks',          instructions: 'THE, AND, ING, ION, TIO, ENT, ATI, FOR, HER, TER — three-letter combos that are everywhere.',                                                                                keys: 'abcdefghijklmnopqrstuvwxyz ', tip: '' },
  { id: 'lesson-30', title: 'Chapter 30: 100 Most Common Words',   subtitle: 'Focus: Word fluency',                 instructions: 'The 100 most-used words in English. Master these and you can type 50%+ of any text.',                                                                                       keys: 'abcdefghijklmnopqrstuvwxyz ', tip: '' },
  { id: 'lesson-31', title: 'Chapter 31: Sentence Rhythm',         subtitle: 'Focus: Punctuation cues',             instructions: 'Smooth sentences with all the punctuation that real writing uses.',                                                                                                         keys: "abcdefghijklmnopqrstuvwxyz ,.;':\"?-", tip: '' },
  { id: 'lesson-32', title: 'Chapter 32: Code Typing Micro-Drill', subtitle: 'Focus: Real syntactical code',        instructions: 'JavaScript and Python snippets — brackets, semicolons, operators all in motion.',                                                                                            keys: "abcdefghijklmnopqrstuvwxyz0123456789 ()[]{}+-=/<>;:'\".,", tip: '' },
];

export const CHALLENGES = [
  { id: 'daily-challenge',  label: 'Daily Challenge',     desc: "Today's seeded run · resets at midnight" },
  { id: 'speed-run',        label: 'Speed Run Endurance', desc: 'Real English paragraphs testing muscle stamina.' },
  { id: 'expert-sentences', label: 'Punctuation Expert',  desc: 'Complex sentences with quotes, brackets, and syntax.' },
  { id: 'code-sprint',      label: 'Code Syntax Sprint',  desc: 'Real syntactical coding layouts in JS/Python.' },
];
